export const GET_USER_ATTEMPT = 'GET_USERS_ATTEMPT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USERS_ATTEMPT = 'GET_USERS_ATTEMPT';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const FILTER_USERS = 'FILTER_USERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
